spring:
  application:
    name:  demo
  datasource:
    url: jdbc:oracle:thin:@115.90.212.20:10000:XE
    username: KBJ01
    password: KBJ1234
    driver-class-name: oracle.jdbc.OracleDriver
  mvc:
    static-path-pattern: /upload/**
  web:
    resources:
      static-locations: file:uploads/  


servlet:
  multipart:
    max-file-size: 100MB
    max-request-size: 100MB
    
server:
  port: 8081
  
  
  
mybatis:
  configuration:
    jdbc-type-for-null: VARCHAR
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.kh.start.board.model.vo
  mapper-locations: classpath:mapper/*.xml
    
    
jwt:
  secret: H7oIaBujRo6fA/a0wdk09iY6STECQZbemMj8bcs5xBMzd0IYxzT+hNQd+fgXvsyz3qHF3DIwuYXUE9m7w5tkDw==
  
  
  
    