spring:
  application:
    name:  demo
  datasource:
    url: jdbc:oracle:thin:@115.90.212.20:10000:XE
    username: KBJ01
    password: KBJ1234
    driver-class-name: oracle.jdbc.driver.OracleDriver

    
server:
  port: 8081