spring:
  application:
    name:  demo
  datasource:
    url: jdbc:oracle:thin:@115.90.212.20:10000:XE
    username: KBJ01
    password: KBJ1234
    driver-class-name: oracle.jdbc.driver.OracleDriver

    
server:
  port: 8081
  
  
naver:
  client:
    id: Kki4fyVYcYf_zkU2HAq8
    secret: q6k43VptHS
  redirect:
    url: http://localhost:8081/login/naver   